AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function urls + CloudFront sample using kotlin/native.

Resources:
  lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./build/lambda/lambda.zip
      Description: Lambda function URL using kotlin/native.
      FunctionName: !Sub ${AWS::StackName}-lambda
      Handler: notUsed
      MemorySize: 128
      Role: !GetAtt iamRole.Arn
      Runtime: provided.al2
      Timeout: 3

  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  invokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt lambda.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: AWS_IAM
      SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${distribution}
#      FunctionUrlAuthType: NONE

  url:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref lambda
      AuthType: AWS_IAM
#  url:
#    Type: AWS::Lambda::Url
#    Properties:
#      TargetFunctionArn: !Ref lambda
#      AuthType: NONE

  distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt url.FunctionUrl]]
            Id: "DefaultOriginLambda"
            OriginAccessControlId: !Ref cloudFrontOriginAccessControl
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: "DefaultOriginLambda"
          ViewerProtocolPolicy: https-only
          # AllViewerExceptHostHeader - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
          OriginRequestPolicyId: "b689b0a8-53d0-40ab-baf2-68738e2966ac"
          # CachingDisabled policy - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html.
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
        Enabled: true
        PriceClass: PriceClass_100

  cloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Allow CloudFront to access lambda url
        Name: LambdaUrlAccess
        OriginAccessControlOriginType: lambda
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  lambdaUrl:
    Value: !GetAtt url.FunctionUrl
  cloudFrontUrl:
    Value: !GetAtt distribution.DomainName
